'use strict';

(function () {

  // Константы
  var COUNT_ADVERTISING = 5;

  var PIN_BUTTON_IMG_WIDTH = 40;
  var PIN_BUTTON_IMG_HEIGHT = 40;

  var LOCATION_PIN_MIN_X = 0;
  var LOCATION_PIN_MAX_X = 630;

  var LOCATION_PIN_MIN_Y = 130;
  var LOCATION_PIN_MAX_Y = 630;

  var PHOTO_ARRAY_LENGTH_MIN = 0;
  var PHOTO_ARRAY_LENGTH_MAX = 30;

  var PRICE_MIN = 1000;
  var PRICE_MAX = 5000;

  var PRICE_BUNGALO = 0;
  var PRICE_FLAT = 1000;
  var PRICE_HOUSE = 5000;
  var PRICE_PALACE = 10000;
  var PRICE_DEFAULT = 'Выберите тип жилья';

  var CoordY = {
    MIN: 200,
    MAX: 600
  };

  var MainPinSize = {
    WIDTH: 62,
    HEIGHT: 62,
    ARROW: 18
  };

  var offsetY = MainPinSize.HEIGHT + MainPinSize.ARROW;

  window.constants = {
    COUNT_ADVERTISING: COUNT_ADVERTISING,
    PIN_BUTTON_IMG_WIDTH: PIN_BUTTON_IMG_WIDTH,
    PIN_BUTTON_IMG_HEIGHT: PIN_BUTTON_IMG_HEIGHT,
    LOCATION_PIN_MIN_X: LOCATION_PIN_MIN_X,
    LOCATION_PIN_MAX_X: LOCATION_PIN_MAX_X,
    LOCATION_PIN_MIN_Y: LOCATION_PIN_MIN_Y,
    LOCATION_PIN_MAX_Y: LOCATION_PIN_MAX_Y,
    PHOTO_ARRAY_LENGTH_MIN: PHOTO_ARRAY_LENGTH_MIN,
    PHOTO_ARRAY_LENGTH_MAX: PHOTO_ARRAY_LENGTH_MAX,
    PRICE_MIN: PRICE_MIN,
    PRICE_MAX: PRICE_MAX,
    PRICE_BUNGALO: PRICE_BUNGALO,
    PRICE_FLAT: PRICE_FLAT,
    PRICE_HOUSE: PRICE_HOUSE,
    PRICE_PALACE: PRICE_PALACE,
    PRICE_DEFAULT: PRICE_DEFAULT,
    CoordY: CoordY,
    MainPinSize: MainPinSize,
    offsetY: offsetY
  };
})();
